name: CI
on:
  push:
    branches:
      - master
jobs:
  build-and-push:
    name: 'Build and push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      #pipe no run indica quebra de linha para rodar vários comandos
      #GITHUB_SHA contém a hash do commit
      #head -c7 returna os primeiros 7 caracteres
      #GITHUB_OUTPUT armazena returnos de steps
      - name: Generate SHA
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT
      #logar no registry
      #usar action do marketplace 
      #utilizar token no lugar da senha e secrets do repositório

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image
        run: docker build -t gu1guizo/tcc.orders_companydash_worker:${{ steps.generate_sha.outputs.sha }} .

      #push image
      #troca tag para a latest
      #permite rollbacks
      - name: Push docker image
        run: |
          docker push gu1guizo/tcc.orders_companydash_worker:${{ steps.generate_sha.outputs.sha }}
          docker tag gu1guizo/tcc.orders_companydash_worker:${{ steps.generate_sha.outputs.sha }} gu1guizo/nlw-journey.api:latest
          docker push gu1guizo/tcc.orders_companydash_worker:latest



